
export const URL = "http://localhost:3001"

export const admin = {
    GET_ALL_REPORTS: "GET_ALL_REPORTS",
    GET_DETAIL_REPORT: "GET_DETAIL_REPORT",
    DELETE_REPORT: "DELETE_REPORT",
    ADD_TAG: "ADD_TAG",
    DELETE_TAG: "DELETE_TAG",
    BAN_USER: "BAN_USER"
};

export const comment = {
    ADD_COMMENT: "ADD_COMMENT",
    UPDATE_COMMENT: "UPDATE_COMMENT",
    DELETE_COMMENT: "DELETE_COMMENT",
    ORDER_BY_DATE: "ORDER_BY_DATE",
};

export const favorite = {
    GET_FAVOURITE: "GET_FAVORITE",
    SET_FAVORITE: "SET_FAVORITE"    
};

export const inbox = {
    USER_INBOX: "USER_INBOX",
    VIEW_NOTIFICATION: "VIEW_NOTIFICATION",
    DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
    CLEAN_INBOX: "CLEAN_INBOX"
};

export const like = {
    GET_LIKES: "GET_LIKES",
    SET_LIKES_BY_USER: "SET_LIKES_BY_USER"
};

export const module = {
    GET_MODULES: "GET_MODULES"
};

export const question = {
    GET_QUESTIONS: "GET_QUESTIONS",
    GET_QUESTION_DETAILS: "GET_QUESTION_DETAILS",
    GET_QUESTIONS_BY_NAME: "GET_QUESTIONS_BY_NAME",
    CREATE_QUESTION: "CREATE_QUESTION",
    UPDATE_QUESTION: "UPDATE_QUESTION",
    DELETE_QUESTION: "DELETE_QUESTION",
    ORDER_BY_DATE: "ORDER_BY_DATE",
    ORDER_BY_MODULE: "ORDER_BY_MODULE",
    ORDER_BY_TAG: "ORDER_BY_TAG"
};

export const report = {
    SEND_REPORT: "SEND_REPORT"
};

export const tag = {
    GET_TAGS: "GET_TAGS"
};

export const user = {
    CREATE_USER: "CREATE_USER",
    GET_USERS: "GET_USERS",
    GET_USERS_BY_NAME: "GET_USERS_BY_NAME",
    GET_USER_PROFILE: "GET_USER_PROFILE",
    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE"
};
